version: "3.8"

services:

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    networks:
      - tjms
    ports:
      - "9191:9191"
    expose:
      - "9191"
  alvara:
    build:
      context: ./alvara
      dockerfile: Dockerfile
    networks:
      - tjms
    ports:
      - "8081:8081"
    expose:
      - "8081"
  funcionario:
    build:
      context: ./funcionario
      dockerfile: Dockerfile
    networks:
      - tjms
    ports:
      - "8082:8082"
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    networks:
      - tjms
    ports:
      - "8761:8761"
    expose:
      - "8761"

networks:
  tjms:
    name: tjms
    driver: "bridge"
